# Generated by Django 5.2.3 on 2025-07-03 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edufeedbackhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='edufeedbackhub.comment')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='edufeedbackhub.universityranking')),
            ],
        ),
    ]
