# Generated by Django 5.2.3 on 2025-07-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edufeedbackhub', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='universityranking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='universityranking',
            name='region',
        ),
        migrations.AddField(
            model_name='universityranking',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='edufeedbackhub.university'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='edufeedbackhub.university'),
        ),
    ]
