# Generated by Django 5.2.3 on 2025-07-15 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edufeedbackhub', '0002_remove_lecturer_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='department',
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('school', 'name')},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Whether the comment is anonymous (for students)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='school',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='edufeedbackhub.school'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
