# Generated by Django 5.2.4 on 2025-07-23 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edufeedbackhub', '0006_alter_rating_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('lecturer_id', models.IntegerField(blank=True, null=True)),
                ('lecturer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('university_id', models.IntegerField(blank=True, null=True)),
                ('university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('college_id', models.IntegerField(blank=True, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('school_id', models.IntegerField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('module_name', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
